# -*- mode: ruby -*-
# vi: set ft=ruby :
servers=[
      {
        :hostname => "master",
        :ip => "192.168.56.10",
        :box => "centos/stream8",
        :ram => 2048,
        :cpu => 2,
        :name => "master"
      },
      {
        :hostname => "worker",
        :ip => "192.168.56.11",
        :box => "centos/stream8",
        :ram => 2048,
        :cpu => 2,
        :name => "worker"
      },
      {
        :hostname => "nfs",
        :ip => "192.168.56.12",
        :box => "centos/stream8",
        :ram => 2048,
        :cpu => 2,
        :name => "nfs"
      }
]

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network "private_network", ip: machine[:ip]
          node.vm.provider "virtualbox" do |vb|
              vb.customize ["modifyvm", :id, "--memory", machine[:ram], "--cpus", machine[:cpu], "--name", machine[:name]]
          end
      end
  end
end