apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: pozuelo
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/app
    server: nfs.pozuelo.com